### PR TITLE
add support for Leaflet.hash.js (automatic permalinks for current viewport)

### PR DESCRIPTION
**Pull request by robertharm**
This PR includes the leaflet.js plugin https://github.com/mlevans/leaflet-hash - it automatically adds dynamic URL hashes to web pages with Leaflet maps for better shareability than the current permalink-link which users have to click manually to get a shareable URL.

### CODE REVIEW

**Comment by kamba4** [comment]
Thanks a lot for your pull request. The leaflet-hash plugin seems to be very useful. However I'd like to start with as few plugins as possible. If it appears that many users have problems finding the Permalink function I'll rethink my decision and come back to your request. Thanks!

**Comment by rugk** [comment]
I don't even find the button where to get the permalink. So :+1: for this.

@kamba4 BTW: Why do you have disabled the issues?

**Comment by kamba4** [comment]
There is a new function in the header area of the side bar to create a permalink with the current coordinates. This should be much easier to find than the link in the lower left corner of the map.

**Comment by kamba4** [comment]
Closed pull request because of new permalink function in the header area.

**Comment by rugk** [comment]
> BTW: Why do you have disabled the issues?

?

**Comment by kamba4** [comment]
Just enabled issues.

**Pull request closed without merging**
